# Generated by Django 4.1.4 on 2023-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_test_fio_alter_test_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='FIO',
            field=models.CharField(max_length=30, verbose_name='фио'),
        ),
        migrations.AlterField(
            model_name='test',
            name='data_sdachi',
            field=models.DateField(verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='test',
            name='resultat',
            field=models.CharField(max_length=15, verbose_name='Результат'),
        ),
    ]
