# Generated by Django 4.1.5 on 2023-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_test_fio_alter_test_data_sdachi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='IO',
            field=models.CharField(default='', help_text='ваша фамилия', max_length=30, verbose_name='фио'),
            preserve_default=False,
        ),
    ]
