# Generated by Django 4.1.4 on 2023-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_test_io'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='IO',
            field=models.CharField(help_text='паспортные данные', max_length=30, verbose_name='номер и серия паспорта'),
        ),
    ]
