# Generated by Django 4.1.4 on 2023-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_test_data_sdachi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='FIO',
            field=models.CharField(help_text='ваша фамилия', max_length=30, null=True, verbose_name='фио'),
        ),
    ]
