# Generated by Django 4.1.4 on 2023-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_test_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='resultat',
            field=models.CharField(blank=True, help_text='ваш результат на ковид', max_length=15, null=True, verbose_name='Результат'),
        ),
    ]
