# Generated by Django 4.1.4 on 2023-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_test_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='FIO',
            field=models.CharField(blank=True, help_text='ваша фамилия', max_length=30, null=True, verbose_name='фио'),
        ),
        migrations.AlterField(
            model_name='test',
            name='IO',
            field=models.CharField(blank=True, help_text='паспортные данные', max_length=30, null=True, verbose_name='номер и серия паспорта'),
        ),
        migrations.AlterField(
            model_name='test',
            name='data_sdachi',
            field=models.DateField(blank=True, help_text='дата вашего теста', null=True, verbose_name='Дата сдачи'),
        ),
    ]
